/*
 * enfle-plugintype.h -- enfle plugin type definition
 * (C)Copyright 2000-2004 by Hiroshi Takekawa
 * This file is part of Enfle.
 *
 * Last Modified: Tue Mar  9 22:00:17 2004.
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

#ifndef _ENFLE_PLUGINTYPE_H
#define _ENFLE_PLUGINTYPE_H

typedef enum {
  ENFLE_PLUGIN_INVALID = -1,
  ENFLE_PLUGIN_START = 0,
  ENFLE_PLUGIN_UI = ENFLE_PLUGIN_START,
  ENFLE_PLUGIN_VIDEO,
  ENFLE_PLUGIN_AUDIO,
  ENFLE_PLUGIN_LOADER,
  ENFLE_PLUGIN_SAVER,
  ENFLE_PLUGIN_PLAYER,
  ENFLE_PLUGIN_STREAMER,
  ENFLE_PLUGIN_ARCHIVER,
  ENFLE_PLUGIN_EFFECT,
  ENFLE_PLUGIN_AUDIODECODER,
  ENFLE_PLUGIN_VIDEODECODER,
  ENFLE_PLUGIN_DEMULTIPLEXER,
  ENFLE_PLUGIN_END
} PluginType;

#endif
